version: '3.8'

services:
  backend:
    image: scale112/gmb-boost-pro-backend:latest
    container_name: gmb-boost-pro-backend-hub
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      # Google OAuth Configuration
      - GOOGLE_CLIENT_ID=52772597205-9ogv54i6sfvucse3jrqj1nl1hlkspcv1.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - FRONTEND_URL=https://polite-wave-08ec8c90f.1.azurestaticapps.net
      - BACKEND_URL=https://scale12345-hccmcmf7g3bwbvd0.canadacentral-01.azurewebsites.net
      - GOOGLE_REDIRECT_URI=https://polite-wave-08ec8c90f.1.azurestaticapps.net/auth/google/callback
      - HARDCODED_ACCOUNT_ID=106433552101751461082
      # Razorpay Configuration
      - RAZORPAY_KEY_ID=rzp_live_RFSzT9EvJ2cwJI
      - RAZORPAY_KEY_SECRET=7i0iikfS6eO7w4DSLXldCBX5
      - RAZORPAY_WEBHOOK_SECRET=gmb_boost_pro_webhook_secret_2024
      # Azure OpenAI Configuration - NOW HARDCODED IN SOURCE CODE
      # No environment variables needed for AI features anymore!
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/health', (res) => { if (res.statusCode === 200) { process.exit(0) } else { process.exit(1) } })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - gmb-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  gmb-network:
    driver: bridge